In [1]:
import pandas as pd

In [4]:
pd.read_csv('../data/raw/data.outcome.csv')

,Unnamed: 0,aid,Equity,Equity_cat,Outcome,Outcome_notes
0,1,1,0,NaN,soc_rel,Does not explicitly tie outcomes to presence o...
1,2,1,0,NaN,soc_rel,Does not explicitly tie outcomes to presence o...
2,3,1,0,NaN,gov,Does not explicitly tie outcomes to presence o...
3,4,1,0,NaN,gov,Does not explicitly tie outcomes to presence o...
4,5,1,0,NaN,soc_rel,Does not explicitly tie outcomes to presence o...
5,6,1,0,NaN,soc_rel,Does not explicitly tie outcomes to presence o...
6,7,1,0,NaN,gov,Does not explicitly tie outcomes to presence o...
7,8,1,0,NaN,gov,Does not explicitly tie outcomes to presence o...
8,9,2,0,NaN,gov,NaN
9,10,2,0,NaN,gov,NaN
10,11,2,0,NaN,gov,NaN
11,12,2,0,NaN,sub_well,NaN
12,13,2,0,NaN,sub_well,NaN
13,14,2,0,NaN,sub_well,NaN
14,15,2,0,NaN,gov,NaN
15,16,2,0,NaN,gov,NaN
16,17,2,0,NaN,gov,NaN
17,18,2,0,NaN,sub_well,NaN
18,19,2,0,NaN,sub_well,NaN
19,20,2,0,NaN,sub_well,NaN
20,21,2,0,NaN,gov,NaN
21,22,2,0,NaN,gov,NaN
22,23,2,0,NaN,gov,NaN
23,24,2,0,NaN,sub_well,NaN
24,25,2,0,NaN,sub_well,NaN
25,26,2,0,NaN,sub_well,NaN
26,27,3,0,NaN,eco_liv_std,NaN
27,28,4,1,NaN,education,NaN
28,29,4,1,NaN,soc_rel,NaN
29,30,4,1,NaN,gov,NaN
...,...,...,...,...,...,...
12038,12039,1100,0,NaN,eco_liv_std,NaN
12039,12040,1102,0,NaN,eco_liv_std,NaN
12040,12041,1103,0,NaN,env,NaN
12041,12042,1103,0,NaN,mat_liv_std,NaN
12042,12043,1103,0,NaN,eco_liv_std,NaN
12043,12044,1104,0,NaN,mat_liv_std,NaN
12044,12045,1104,0,NaN,eco_liv_std,NaN
12045,12046,1105,0,NaN,mat_liv_std,NaN
12046,12047,1105,0,NaN,education,NaN
12047,12048,1107,0,NaN,eco_liv_std,NaN
12048,12049,1108,0,NaN,mat_liv_std,NaN
12049,12050,1108,0,NaN,eco_liv_std,NaN
12050,12051,1108,0,NaN,health,NaN
12051,12052,1109,0,NaN,env,NaN
12052,12053,1109,0,NaN,mat_liv_std,NaN
12053,12054,1109,0,NaN,eco_liv_std,NaN
12054,12055,1110,0,NaN,eco_liv_std,NaN
12055,12056,1111,0,NaN,eco_liv_std,NaN
12056,12057,1112,0,NaN,eco_liv_std,NaN
12057,12058,1112,0,NaN,health,NaN
12058,12059,1112,0,NaN,education,NaN
12059,12060,1113,0,NaN,env,NaN
12060,12061,1113,0,NaN,mat_liv_std,NaN
12061,12062,1113,0,NaN,eco_liv_std,NaN
12062,12063,1114,0,NaN,env,NaN
12063,12064,1114,0,NaN,mat_liv_std,NaN
12064,12065,1114,0,NaN,eco_liv_std,NaN
12065,12066,1115,0,NaN,eco_liv_std,NaN
12066,12067,1115,0,NaN,soc_rel,NaN
12067,12068,1115,0,NaN,gov,NaN